config/routes.rb
Rails.application.routes.draw do
  resources :venta
  resources :articles
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/venta.rb
class Venta < ApplicationRecord
  belongs_to :article

  def self.sales_by_product
    grouped_articles = all.group_by(&:article_id)
    total_sales = grouped_articles.each_key{ |article_id| grouped_articles[article_id] = grouped_articles[article_id].map{|sale| sale.sale_price}.sum }
    total_sales.transform_keys{ |key| Article.find_by(id: key).strain }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:article_type, :medical_use, :classification, :strain, :category, :brand)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @data_keys = [
      'Enero',
      'Febrero',
      'Marzo',
      'Abril',
      'Mayo',
      'Junio'
    ]

    @data_values = [0,10,5,2,20,30,45]

    @ventas = Venta.sales_by_product
  end
end

app/controllers/venta_controller.rb
class VentaController < ApplicationController
  before_action :set_venta, only: %i[ show edit update destroy ]

  # GET /venta or /venta.json
  def index
    @venta = Venta.sales_by_product
  end

  # GET /venta/1 or /venta/1.json
  def show
  end

  # GET /venta/new
  def new
    @venta = Venta.new
  end

  # GET /venta/1/edit
  def edit
  end

  # POST /venta or /venta.json
  def create
    @venta = Venta.new(venta_params)

    respond_to do |format|
      if @venta.save
        format.html { redirect_to Venta_url(@venta), notice: "Venta was successfully created." }
        format.json { render :show, status: :created, location: @venta }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @venta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venta/1 or /venta/1.json
  def update
    respond_to do |format|
      if @venta.update(Venta_params)
        format.html { redirect_to Venta_url(@venta), notice: "venta was successfully updated." }
        format.json { render :show, status: :ok, location: @venta }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @venta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venta/1 or /venta/1.json
  def destroy
    @venta.destroy!

    respond_to do |format|
      format.html { redirect_to venta_url, notice: "venta was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venta
      @venta = Venta.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def venta_params
      params.require(:venta).permit(:date, :article_id, :sale_price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Article type:</strong>
    <%= article.article_type %>
  </p>

  <p>
    <strong>Medical use:</strong>
    <%= article.medical_use %>
  </p>

  <p>
    <strong>Classification:</strong>
    <%= article.classification %>
  </p>

  <p>
    <strong>Strain:</strong>
    <%= article.strain %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= article.category %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= article.brand %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :article_type, style: "display: block" %>
    <%= form.text_field :article_type %>
  </div>

  <div>
    <%= form.label :medical_use, style: "display: block" %>
    <%= form.text_field :medical_use %>
  </div>

  <div>
    <%= form.label :classification, style: "display: block" %>
    <%= form.text_field :classification %>
  </div>

  <div>
    <%= form.label :strain, style: "display: block" %>
    <%= form.text_field :strain %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Home#index</h1>
            <p>Chart using <code>Chart.js</code></p>

            <div class="mx-auto pt-3" style="width: 800px;">
                <canvas 
                    id="sales"
                    data-controller="chart"
                    data-chart-sales-value="<%= @ventas.to_json %>"
                >
                </canvas>
            </div>
        
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChartMonolith</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/venta/_form.html.erb
<%= form_with(model: ventum) do |form| %>
  <% if ventum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ventum.errors.count, "error") %> prohibited this ventum from being saved:</h2>

      <ul>
        <% ventum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :article_id, style: "display: block" %>
    <%= form.text_field :article_id %>
  </div>

  <div>
    <%= form.label :sale_price, style: "display: block" %>
    <%= form.text_field :sale_price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/venta/_ventum.html.erb
<div id="<%= dom_id ventum %>">
  <p>
    <strong>Date:</strong>
    <%= ventum.date %>
  </p>

  <p>
    <strong>Article:</strong>
    <%= ventum.article_id %>
  </p>

  <p>
    <strong>Sale price:</strong>
    <%= ventum.sale_price %>
  </p>

</div>

app/views/venta/edit.html.erb
<h1>Editing ventum</h1>

<%= render "form", ventum: @ventum %>

<br>

<div>
  <%= link_to "Show this ventum", @ventum %> |
  <%= link_to "Back to venta", venta_path %>
</div>

app/views/venta/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Venta</h1>

<div id="venta">
  <%= @venta %>
</div>

<%= link_to "New ventum", new_ventum_path %>

app/views/venta/new.html.erb
<h1>New ventum</h1>

<%= render "form", ventum: @ventum %>

<br>

<div>
  <%= link_to "Back to venta", venta_path %>
</div>

app/views/venta/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ventum %>

<div>
  <%= link_to "Edit this ventum", edit_ventum_path(@ventum) %> |
  <%= link_to "Back to venta", venta_path %>

  <%= button_to "Destroy this ventum", @ventum, method: :delete %>
</div>